apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ui
spec:
  selector:
    app: rabbitmq
    tier: backend
  ports:
    - protocol: "TCP"
      port: 15672
      targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
    tier: backend
  ports:
    - protocol: "TCP"
      port: 5672
      targetPort: 5672

---
apiVersion: v1
kind: Endpoints
metadata:
  name: rabbitmq
subsets:
  - addresses:
      - ip: 192.168.39.180
    ports:
      - port: 5672

---
apiVersion: v1
kind: Endpoints
metadata:
  name: rabbitmq-ui
subsets:
  - addresses:
      - ip: 192.168.39.180
    ports:
      - port: 15672
