apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: backend
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:3-management
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5672
            - containerPort: 15672
