apiVersion: v1
kind: Service
metadata:
  name: brands-api
spec:
  selector:
    app: brands-api
    tier: backend
  ports:
    - port: 8080
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: categories-api
spec:
  selector:
    app: categories-api
    tier: backend
  ports:
    - port: 8080
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: products-api
spec:
  selector:
    app: products-api
    tier: backend
  ports:
    - port: 8080
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: suppliers-api
spec:
  selector:
    app: suppliers-api
    tier: backend
  ports:
    - port: 8080
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: authorization-service
spec:
  selector:
    app: authorization-service
    tier: backend
  ports:
    - port: 8080
      targetPort: 80
